databases:
  - name: transplantcentral
    databaseName: transplantcentral
    user: transplantcentral

services:
  - type: web
    name: transplantcentral
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: transplantcentral
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
